import PptxGenJS from 'pptxgenjs'
import { PlateConfig, MetadataLayer, Plate } from '@/types/plate'
import { wellAddress, rowIndexToLabel } from '@/lib/plate/wellAddressing'
import { PptxExportOptions } from '@/types/export'

function addPlateLayerSlides(pptx: PptxGenJS, config: PlateConfig, layers: MetadataLayer[], plateName?: string) {
  for (const layer of layers) {
    const slide = pptx.addSlide()

    // Title: "PlateName — LayerName" or just "LayerName"
    const title = plateName ? `${plateName} — ${layer.name}` : layer.name
    slide.addText(title, {
      x: 0.3,
      y: 0.2,
      w: 9,
      h: 0.5,
      fontSize: 18,
      bold: true,
      color: '333333',
    })

    const tableRows: PptxGenJS.TableRow[] = []

    // Header row
    const headerCells: PptxGenJS.TableCell[] = [
      { text: '', options: { fill: { color: 'E5E5E5' }, bold: true, fontSize: 8, align: 'center' } },
    ]
    for (let c = 0; c < config.columns; c++) {
      headerCells.push({
        text: String(c + 1),
        options: { fill: { color: 'E5E5E5' }, bold: true, fontSize: 8, align: 'center' },
      })
    }
    tableRows.push(headerCells)

    // Data rows
    for (let r = 0; r < config.rows; r++) {
      const cells: PptxGenJS.TableCell[] = [
        {
          text: rowIndexToLabel(r),
          options: { fill: { color: 'E5E5E5' }, bold: true, fontSize: 8, align: 'center' },
        },
      ]

      for (let c = 0; c < config.columns; c++) {
        const addr = wellAddress(r, c)
        const val = layer.values[addr]
        const color = val !== null && val !== undefined && val !== ''
          ? layer.colorMap[String(val)]?.replace('#', '') || 'FFFFFF'
          : 'F5F5F5'

        const brightness = getBrightness(color)

        cells.push({
          text: val !== null && val !== undefined ? String(val) : '',
          options: {
            fill: { color },
            fontSize: 6,
            align: 'center',
            color: brightness < 128 ? 'FFFFFF' : '333333',
          },
        })
      }

      tableRows.push(cells)
    }

    const colWidth = Math.min(0.7, 8.5 / (config.columns + 1))
    const rowHeight = Math.min(0.4, 4.5 / (config.rows + 1))

    slide.addTable(tableRows, {
      x: 0.3,
      y: 0.8,
      colW: colWidth,
      rowH: rowHeight,
      border: { type: 'solid', pt: 0.5, color: 'D1D5DB' },
      autoPage: false,
    })

    // Legend
    const uniqueValues = Object.entries(layer.colorMap)
    if (uniqueValues.length > 0) {
      const legendY = 0.8 + (config.rows + 1) * rowHeight + 0.3
      slide.addText('Legend:', {
        x: 0.3,
        y: legendY,
        w: 1,
        h: 0.3,
        fontSize: 10,
        bold: true,
        color: '333333',
      })

      uniqueValues.forEach(([value, hexColor], i) => {
        const x = 0.3 + (i % 4) * 2.3
        const y = legendY + 0.3 + Math.floor(i / 4) * 0.3

        slide.addShape(pptx.ShapeType.rect, {
          x,
          y,
          w: 0.2,
          h: 0.2,
          fill: { color: hexColor.replace('#', '') },
          line: { color: 'D1D5DB', width: 0.5 },
        })

        slide.addText(value, {
          x: x + 0.25,
          y,
          w: 2,
          h: 0.2,
          fontSize: 8,
          color: '666666',
        })
      })
    }
  }
}

export async function exportPptx(
  config: PlateConfig,
  layers: MetadataLayer[],
  options: PptxExportOptions,
  suffix: string = ''
) {
  const pptx = new PptxGenJS()
  pptx.author = 'MetaBuilder'
  pptx.title = options.title || 'Plate Layout'

  if (options.includeDescriptionSlides && options.experimentDescription) {
    const titleSlide = pptx.addSlide()
    titleSlide.addText(options.title || 'Experiment Plate Layout', {
      x: 0.5, y: 1.5, w: 9, h: 1,
      fontSize: 28, bold: true, color: '333333',
    })
    titleSlide.addText(options.experimentDescription, {
      x: 0.5, y: 2.8, w: 9, h: 3,
      fontSize: 14, color: '666666', valign: 'top',
    })
    titleSlide.addText('Generated by MetaBuilder', {
      x: 0.5, y: 6.5, w: 9, h: 0.5,
      fontSize: 10, color: '999999', italic: true,
    })
  }

  addPlateLayerSlides(pptx, config, layers)

  await pptx.writeFile({ fileName: `plate-layout${suffix}.pptx` })
}

/** Consolidated multi-plate PPTX — all plates in one presentation */
export async function exportPptxMultiPlate(
  plates: Plate[],
  options: PptxExportOptions,
) {
  const pptx = new PptxGenJS()
  pptx.author = 'MetaBuilder'
  pptx.title = options.title || 'Plate Layout'

  // Title slide
  if (options.includeDescriptionSlides && options.experimentDescription) {
    const titleSlide = pptx.addSlide()
    titleSlide.addText(options.title || 'Experiment Plate Layout', {
      x: 0.5, y: 1.5, w: 9, h: 1,
      fontSize: 28, bold: true, color: '333333',
    })
    titleSlide.addText(options.experimentDescription, {
      x: 0.5, y: 2.8, w: 9, h: 3,
      fontSize: 14, color: '666666', valign: 'top',
    })
    titleSlide.addText(`${plates.length} plate${plates.length !== 1 ? 's' : ''} — Generated by MetaBuilder`, {
      x: 0.5, y: 6.5, w: 9, h: 0.5,
      fontSize: 10, color: '999999', italic: true,
    })
  }

  // Add slides for each plate, using plate name as prefix in slide titles
  for (const plate of plates) {
    addPlateLayerSlides(pptx, plate.config, plate.layers, plate.name)
  }

  await pptx.writeFile({ fileName: 'plate-layout.pptx' })
}

function getBrightness(hex: string): number {
  const clean = hex.replace('#', '')
  const r = parseInt(clean.slice(0, 2), 16)
  const g = parseInt(clean.slice(2, 4), 16)
  const b = parseInt(clean.slice(4, 6), 16)
  return (r * 299 + g * 587 + b * 114) / 1000
}
